enabled: "true"
usePlaceholderAPI: "true"
enableStatistics: "true"
enableRecords: "true"
selfhugCountsStatistics: "true"
cooldown: "10"
translation:
  hugSyntaxError: "&3Hugger &8>> &cSyntax Error. Usage: /hug [player]"
  playerNotFoundError: "&3Hugger &8>> &7The player you specified is not currently online"
  configReloaded: "&3Hugger &8>> &7Configuration successfully reloaded!"
  incorrectUsage: "&3Hugger &8>> &cIncorrect usage of command. Refer to `/hugger help` for syntax"
  playerStatsHeader: "&3 Player stats for: &7%s"
  hugsSentStat: "&3 Hugs sent: &7%s"
  hugsReceivedStat: "&3 Hugs received: &7%s"
  newRecord: "&3Hugger &8>> &7Congratulations! You beat the record for most hugged person on the server! The old record-holder was: %s"
  newRecordBroadcast: "&3Hugger &8>> &7%s just beat the record for most hugged player! They now have %s hugs."
  recordInfoTitle: "&3Hugger &8>> &7Record information:"
  recordInfo: "&3Current holder: &7%s\n&3Current record: &7%s"
  permissionDenied: "&3Hugger &8>> &cPermission Denied! &7(%s)"
  cooldownReached: "&3Hugger &8>> &cCooldown reached! &7(%ss / %ss)"
effects:
  - chatMessage:
      gotHugged: "&3Hugger &8>> &7You got hugged by: %s"
      huggingPlayer: "&3Hugger &8>> &7Hugging: %s"
  - actionBar:
      gotHugged: "&3Hugger &8>> &7You got hugged by: %s"
      huggingPlayer: "&3Hugger &8>> &7Hugging: %s"
  - title:
      gotHugged: "%s;&7Hugged you"
      huggingPlayer: ""
  - broadcast:
      message: "&3Hugger &8>> %s &7got hugged by %s! "
  - sound:
      sound: "BLOCK_NOTE_BLOCK_IRON_XYLOPHONE"
  - particle:
      type: "HEART"