# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_author: Erb3
site_description: The wiki for the Hugger plugin for Minecraft
site_name: Hugger Wiki
edit_uri: ""
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.instant
    - navigation.tracking
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Erb3/Hugger
      name: Hugger on GitHub
  generator: false
repo_url: https://github.com/Erb3/Hugger
repo_name: Hugger
